
import play.sbt.PlayImport.PlayKeys.playDefaultPort
import uk.gov.hmrc.DefaultBuildSettings
import uk.gov.hmrc.DefaultBuildSettings.{defaultSettings, scalaSettings, targetJvm}

val appName = "personal-details-validation"

lazy val playSettings: Seq[Setting[?]] = Seq(
  routesImport ++= Seq(
    "uk.gov.hmrc.personaldetailsvalidation.model.ValidationId",
    "uk.gov.hmrc.play.pathbinders.PathBinders._"
  )
)

lazy val scoverageSettings: Seq[Def.Setting[? >: String & Double & Boolean]] = {
  import scoverage.*
  Seq(
    ScoverageKeys.coverageExcludedPackages := "<empty>;Reverse.*.*BuildInfo.*;.*config.*;.*Routes.*;.*RoutesPrefix.*;",
    ScoverageKeys.coverageMinimumStmtTotal := 75,
    ScoverageKeys.coverageFailOnMinimum := true,
    ScoverageKeys.coverageHighlighting := true
  )
}
ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "2.13.16"

lazy val it = project
  .enablePlugins(PlayScala)
  .dependsOn(microservice % "test->test") // the "test->test" allows reusing test code and test dependencies
  .settings(DefaultBuildSettings.itSettings(forkJvmPerTest = true))

lazy val microservice = Project(appName, file("."))
  .enablePlugins(Seq(play.sbt.PlayScala, SbtDistributablesPlugin) *)
  .settings(scalaSettings *)
  .disablePlugins(JUnitXmlReportPlugin)
  .settings((playSettings ++ scoverageSettings) *)
  .settings(playDefaultPort := 9967)
  .settings(defaultSettings() *)
  .settings(
    scalacOptions ++= Seq(
      "-deprecation",
      "-feature",
      "-language:implicitConversions",
      "-language:reflectiveCalls",
      "-language:postfixOps"
    ),
    libraryDependencies ++= AppDependencies(),
    retrieveManaged := true
  )
  .settings(
    // silence all warnings on autogenerated files
    scalacOptions += s"-Wconf:src=${target.value}/.*:s"
  )
